aws:
  s3:
    access-id:
    access-pw:
    bucket:

## MYSQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dw_501
    username: root
    password: '06251003'
  jpa:
    database: mysql
    generate-ddl: true
    ddl-auto: update
    show-sql: true
    # format_sql: true
    # h2:
    # console:
    #   enabled: true
# ## MYSQL
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://localhost:3306/dw_501
# spring.datasource.username=root
# spring.datasource.password=06251003
# spring.datasource.initialization-mode=always
# spring.datasource.schema=classpath:init.sql

# ## JPA
# spring.jpa.database=mysql
# spring.jpa.generate-ddl=true
# spring.jpa.hibernate.ddl.auto=update
# spring.jpa.show-sql=true
